// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyecto_centauro.Data;

#nullable disable

namespace proyecto_centauro.Migrations
{
    [DbContext(typeof(BBDDContext))]
    [Migration("20250331115501_AgregarTablaSucursales")]
    partial class AgregarTablaSucursales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("proyecto_centauro.Models.Alquiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fechainicio")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HorarioDevolucion")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HorarioRecogida")
                        .HasColumnType("TEXT");

                    b.Property<string>("LugarDevolucion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LugarRecogida")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsersId");

                    b.ToTable("Alquileres");
                });

            modelBuilder.Entity("proyecto_centauro.Models.Coche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GrupoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Num_maletas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Num_plazas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Num_puertas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Posee_aire_acondicionado")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo_cambio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo_coche")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("SucursalId");

                    b.ToTable("Coches");
                });

            modelBuilder.Entity("proyecto_centauro.Models.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("proyecto_centauro.Models.GrupoAlquiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlquilerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrupoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlquilerId");

                    b.HasIndex("GrupoId");

                    b.ToTable("GrupoAlquiler");
                });

            modelBuilder.Entity("proyecto_centauro.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PorcentajeDescuento")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("proyecto_centauro.Models.ServicioAlquiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlquilerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServicioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlquilerId");

                    b.HasIndex("ServicioId");

                    b.ToTable("ServicioAlquiler");
                });

            modelBuilder.Entity("proyecto_centauro.Models.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("proyecto_centauro.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Movil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("proyecto_centauro.Models.Alquiler", b =>
                {
                    b.HasOne("proyecto_centauro.Models.Usuario", "Usuario")
                        .WithMany("Alquileres")
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("proyecto_centauro.Models.Coche", b =>
                {
                    b.HasOne("proyecto_centauro.Models.Grupo", "Grupo")
                        .WithMany("Coches")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyecto_centauro.Models.Sucursal", "Sucursal")
                        .WithMany("Coches")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Grupo");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("proyecto_centauro.Models.GrupoAlquiler", b =>
                {
                    b.HasOne("proyecto_centauro.Models.Alquiler", "Alquiler")
                        .WithMany("GrupoAlquileres")
                        .HasForeignKey("AlquilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyecto_centauro.Models.Grupo", "Grupo")
                        .WithMany("GrupoAlquileres")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alquiler");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("proyecto_centauro.Models.ServicioAlquiler", b =>
                {
                    b.HasOne("proyecto_centauro.Models.Alquiler", "Alquiler")
                        .WithMany("ServicioAlquileres")
                        .HasForeignKey("AlquilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyecto_centauro.Models.Servicio", "Servicio")
                        .WithMany("ServicioAlquileres")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alquiler");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("proyecto_centauro.Models.Alquiler", b =>
                {
                    b.Navigation("GrupoAlquileres");

                    b.Navigation("ServicioAlquileres");
                });

            modelBuilder.Entity("proyecto_centauro.Models.Grupo", b =>
                {
                    b.Navigation("Coches");

                    b.Navigation("GrupoAlquileres");
                });

            modelBuilder.Entity("proyecto_centauro.Models.Servicio", b =>
                {
                    b.Navigation("ServicioAlquileres");
                });

            modelBuilder.Entity("proyecto_centauro.Models.Sucursal", b =>
                {
                    b.Navigation("Coches");
                });

            modelBuilder.Entity("proyecto_centauro.Models.Usuario", b =>
                {
                    b.Navigation("Alquileres");
                });
#pragma warning restore 612, 618
        }
    }
}
